### ISSUE TITLE
Connect to VPN, but cannot ping or access restricted hosts

### ISSUE THREAD

**Issue by maraal** [dlenski/gp-saml-gui#17]
I had installed `gp-saml-gui` from AUR and I can connect and make the SAML Auth, but i cannot ping or access restrict hosts, by restrict hosts I mean those wich is supposed to be avaliable from the VPN.

Please, tell me if I need to share some log.  I not copy-paste the output of the command here because I am not sure if it is sensible.

Thanks!

**Comment by dlenski** [comment]
> i cannot ping or access restrict hosts, by restrict hosts I mean those wich is supposed to be avaliable from the VPN.

This indicates that something is going wrong with OpenConnect (or the routing/DNS configuration scripts), rather than with `gp-saml-gui`. My best wild guess, in the absence of any other information, would be that you need to submit a [HIP report](https://www.infradead.org/openconnect/hip.html) while connecting to the VPN. Many GlobalProtect VPNs prevent accessing internal resources until it's submitted.

Try running OpenConnect with the `--dump -vvvv` options, compare your routing and DNS configuration before and after connecting, and take a look at existing GlobalProtect-related issues at https://gitlab.com/openconnect/openconnect/issues?state=all&label_name[]=GlobalProtect

**Comment by maraal** [comment]
I would try issue `openconnect --dump -vvvv` but i don't know how to make it authenticate with saml.

**Comment by dlenski** [comment]
> i don't know how to make it authenticate with saml.

…?

You just take the openconnect command [as output by `gp-saml-gui`](https://github.com/dlenski/gp-saml-gui/blob/master/gp-saml-gui.py#L277-L278) and add those arguments to it!

**Comment by maraal** [comment]
Oh, it works! I was trying without the `echo` part, thank you! Its seem to be what you have said, the server asks for a HIP report. I will look for how to do it. Thanks!

**Comment by maraal** [comment]
Thanks, I am able to connect and access the hosts with the generated  HIP
report by the `hipreport.sh` script.
*l.*



Em sex., 18 de set. de 2020 às 15:37, Dan Lenski <notifications@github.com>
escreveu:
